/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'casaflutterapp';
  static const String PLUGIN_VERSION = '1.0.0+8';
  static const String EMAIL = 'assets/images/email.png';
  static const String SPLASH_BACKGROUND = 'assets/images/splash_background.jpeg';
  static const String VERIFY = 'assets/images/verify.png';
}
